var searchData=
[
  ['validation_0',['Validation',['../library_http.html#autotoc_md288',1,'Validation'],['../md__2home_2runner_2work_2pagghiu_8github_8io-source_2pagghiu_8github_8io-source_2SaneCppLibraries_2Libraries_2Http_2AGENTS.html#autotoc_md503',1,'Validation']]],
  ['value_1',['value',['../structSC_1_1VectorMapItem.html#a901ac38f0f4321168ffb31a1cf089db5',1,'SC::VectorMapItem']]],
  ['values_2',['Return values',['../page_coding_style.html#autotoc_md58',1,'']]],
  ['variables_3',['variables',['../page_coding_style.html#autotoc_md73',1,'Globals / Static member variables'],['../page_coding_style.html#autotoc_md66',1,'Member variables']]],
  ['vector_4',['Vector',['../structSC_1_1Vector.html',1,'SC::Vector&lt; T &gt;'],['../library_containers.html#autotoc_md190',1,'Vector']]],
  ['vector_3c_20sc_3a_3avectormapitem_3c_20key_2c_20value_20_3e_20_3e_5',['Vector&lt; SC::VectorMapItem&lt; Key, Value &gt; &gt;',['../structSC_1_1Vector.html',1,'SC']]],
  ['vector_3c_20value_20_3e_6',['Vector&lt; Value &gt;',['../structSC_1_1Vector.html',1,'SC']]],
  ['vectormap_7',['VectorMap',['../structSC_1_1VectorMap.html',1,'SC::VectorMap&lt; Key, Value, Container &gt;'],['../library_containers.html#autotoc_md193',1,'VectorMap']]],
  ['vectormapitem_8',['VectorMapItem',['../structSC_1_1VectorMapItem.html',1,'SC']]],
  ['vectorset_9',['VectorSet',['../structSC_1_1VectorSet.html',1,'SC::VectorSet&lt; Value, Container &gt;'],['../library_containers.html#autotoc_md194',1,'VectorSet']]],
  ['version_10',['Version',['../structSC_1_1HttpParser.html#a2e7a31ffb1e096e00f8aa82a87745e33a34b6cd75171affba6957e308dcbd92be',1,'SC::HttpParser']]],
  ['version_11',['version',['../structSC_1_1PluginIdentity.html#ae9012ed8869c8427c1bacee0a8da0ee2',1,'SC::PluginIdentity']]],
  ['version_20pinning_12',['Version Pinning',['../page_build_external.html#autotoc_md25',1,'']]],
  ['versus_20strict_20mode_13',['Can I benchmark normal mode versus strict mode?',['../page_faq.html#autotoc_md87',1,'']]],
  ['videos_14',['Videos',['../page_build.html#autotoc_md18',1,'Videos'],['../library_async.html#autotoc_md120',1,'Videos'],['../library_async_streams.html#autotoc_md153',1,'Videos'],['../library_file_system_watcher.html#autotoc_md251',1,'Videos'],['../library_http.html#autotoc_md283',1,'Videos'],['../library_plugin.html#autotoc_md338',1,'Videos'],['../library_process.html#autotoc_md348',1,'Videos'],['../library_threading.html#autotoc_md466',1,'Videos']]],
  ['view_15',['view',['../structSC_1_1String.html#a5371d90b41f10577ef37b04406b205d4',1,'SC::String::view()'],['../structSC_1_1StringBuilderFor.html#a646e3ab46b390dc9e63572b06f1e870c',1,'SC::StringBuilderFor::view()']]],
  ['virtual_16',['Virtual',['../page_coding_style.html#autotoc_md74',1,'']]],
  ['virtualallocator_17',['VirtualAllocator',['../structSC_1_1VirtualAllocator.html',1,'SC']]],
  ['virtualarray_18',['VirtualArray',['../structSC_1_1VirtualArray.html',1,'SC']]],
  ['virtualmemory_19',['VirtualMemory',['../structSC_1_1VirtualMemory.html',1,'SC::VirtualMemory'],['../library_memory.html#autotoc_md327',1,'VirtualMemory']]],
  ['visual_20studio_202022_20',['Visual Studio 2022',['../page_building_contributor.html#autotoc_md34',1,'']]],
  ['visual_20studio_20or_20xcode_21',['Visual Studio or XCode',['../page_building_contributor.html#autotoc_md42',1,'']]],
  ['visualization_22',['Dependencies (interactive visualization)',['../page_dependencies.html#autotoc_md2',1,'']]],
  ['visualizers_23',['Does the library have debug visualizers?',['../page_faq.html#autotoc_md90',1,'']]],
  ['volumeserialnumber_24',['volumeSerialNumber',['../structSC_1_1FileDescriptorStat.html#ad17f04920853170200402d6a2b653a82',1,'SC::FileDescriptorStat::volumeSerialNumber'],['../structSC_1_1FileSystemStat.html#aaf5a675d37f10b03bd4beb933be171f4',1,'SC::FileSystemStat::volumeSerialNumber']]],
  ['vs_20class_25',['struct vs class',['../page_coding_style.html#autotoc_md59',1,'']]],
  ['vscode_26',['VSCode',['../page_building_contributor.html#autotoc_md47',1,'']]],
  ['vscode_20ide_20project_20generation_27',['VSCode / IDE project generation',['../page_building_contributor.html#autotoc_md30',1,'']]],
  ['vscode_20on_20linux_28',['VSCode on Linux',['../page_building_contributor.html#autotoc_md38',1,'']]],
  ['vscode_20on_20macos_29',['VScode on macOS',['../page_building_contributor.html#autotoc_md37',1,'']]],
  ['vscode_20on_20macos_20or_20linux_30',['VSCode on macOS or Linux',['../page_building_contributor.html#autotoc_md43',1,'']]],
  ['vscode_20on_20windows_31',['VSCode on Windows',['../page_building_contributor.html#autotoc_md39',1,'VSCode on Windows'],['../page_building_contributor.html#autotoc_md44',1,'VSCode on Windows']]]
];
