var libraries =
[
    [ "Async", "library_async.html", [
      [ "Dependencies", "library_async.html#autotoc_md86", null ],
      [ "What Async Is For", "library_async.html#autotoc_md87", null ],
      [ "Mental Model: Requests Live Until Completion", "library_async.html#autotoc_md88", null ],
      [ "Driving The Event Loop", "library_async.html#autotoc_md89", null ],
      [ "Timers And Cross-Thread Wake-Ups", "library_async.html#autotoc_md90", null ],
      [ "Socket I/O", "library_async.html#autotoc_md91", null ],
      [ "File I/O And Blocking Backends", "library_async.html#autotoc_md92", null ],
      [ "Sequencing And Long-Lived Operations", "library_async.html#autotoc_md93", null ],
      [ "Platform Backends And Tradeoffs", "library_async.html#autotoc_md94", null ],
      [ "Status", "library_async.html#autotoc_md95", null ],
      [ "Videos", "library_async.html#autotoc_md96", null ],
      [ "Blog", "library_async.html#autotoc_md97", null ],
      [ "Roadmap", "library_async.html#autotoc_md98", null ],
      [ "Statistics", "library_async.html#autotoc_md99", null ]
    ] ],
    [ "Async Streams", "library_async_streams.html", [
      [ "Dependencies", "library_async_streams.html#autotoc_md100", null ],
      [ "What Async Streams Is For", "library_async_streams.html#autotoc_md101", null ],
      [ "Mental Model", "library_async_streams.html#autotoc_md102", null ],
      [ "Supplying A Bounded Buffer Pool", "library_async_streams.html#autotoc_md103", null ],
      [ "A File-To-File Pipeline", "library_async_streams.html#autotoc_md104", null ],
      [ "Backpressure And Buffer Lifetime", "library_async_streams.html#autotoc_md105", null ],
      [ "Transforms And Fan-Out", "library_async_streams.html#autotoc_md106", null ],
      [ "Errors, Ending, And Destruction", "library_async_streams.html#autotoc_md107", null ],
      [ "Allocation Model", "library_async_streams.html#autotoc_md108", null ],
      [ "Choosing The Neighboring Abstraction", "library_async_streams.html#autotoc_md109", null ],
      [ "Details", "library_async_streams.html#autotoc_md110", null ],
      [ "Status", "library_async_streams.html#autotoc_md111", null ],
      [ "Videos", "library_async_streams.html#autotoc_md112", null ],
      [ "Blog", "library_async_streams.html#autotoc_md113", null ],
      [ "Roadmap", "library_async_streams.html#autotoc_md114", null ],
      [ "Statistics", "library_async_streams.html#autotoc_md115", null ]
    ] ],
    [ "Await", "library_await.html", [
      [ "Dependencies", "library_await.html#autotoc_md116", null ],
      [ "When Await Fits", "library_await.html#autotoc_md117", null ],
      [ "The Programming Model", "library_await.html#autotoc_md118", null ],
      [ "Coroutine Frame Allocation", "library_await.html#autotoc_md119", null ],
      [ "Structured and Background Tasks", "library_await.html#autotoc_md120", null ],
      [ "Cancellation and Lifetime", "library_await.html#autotoc_md121", null ],
      [ "I/O Shape", "library_await.html#autotoc_md122", null ],
      [ "Examples", "library_await.html#autotoc_md123", null ],
      [ "Platform and Build Boundaries", "library_await.html#autotoc_md124", null ],
      [ "API Reference", "library_await.html#autotoc_md125", null ],
      [ "Status", "library_await.html#autotoc_md126", null ],
      [ "Blog", "library_await.html#autotoc_md127", null ],
      [ "Roadmap", "library_await.html#autotoc_md128", null ],
      [ "Statistics", "library_await.html#autotoc_md129", null ]
    ] ],
    [ "Containers", "library_containers.html", [
      [ "Dependencies", "library_containers.html#autotoc_md130", null ],
      [ "Status", "library_containers.html#autotoc_md131", null ],
      [ "What Containers Is For", "library_containers.html#autotoc_md132", null ],
      [ "Choose The Storage Policy First", "library_containers.html#autotoc_md133", null ],
      [ "A Growable Contiguous Sequence", "library_containers.html#autotoc_md134", null ],
      [ "Put A Hard Bound In The Type", "library_containers.html#autotoc_md135", null ],
      [ "Optimize The Common Case Inline", "library_containers.html#autotoc_md136", null ],
      [ "Small Maps And Sets Stay Linear", "library_containers.html#autotoc_md137", null ],
      [ "Stable Addresses With Generation-Checked Handles", "library_containers.html#autotoc_md138", null ],
      [ "Other Building Blocks", "library_containers.html#autotoc_md139", null ],
      [ "Boundaries With Neighboring Libraries", "library_containers.html#autotoc_md140", null ],
      [ "Allocation, Lifetime, And Failure", "library_containers.html#autotoc_md141", null ],
      [ "Blog", "library_containers.html#autotoc_md142", null ],
      [ "Roadmap", "library_containers.html#autotoc_md143", null ],
      [ "Statistics", "library_containers.html#autotoc_md144", null ]
    ] ],
    [ "Containers Reflection", "library_containers_reflection.html", [
      [ "Dependencies", "library_containers_reflection.html#autotoc_md145", null ],
      [ "What Containers Reflection Is For", "library_containers_reflection.html#autotoc_md146", null ],
      [ "Choose The Adapter Header", "library_containers_reflection.html#autotoc_md147", null ],
      [ "Mental Model", "library_containers_reflection.html#autotoc_md148", null ],
      [ "Nested Containers Need No Per-Field Adapter", "library_containers_reflection.html#autotoc_md149", null ],
      [ "The Same Types Flow Into Serialization", "library_containers_reflection.html#autotoc_md150", null ],
      [ "Boundaries And Tradeoffs", "library_containers_reflection.html#autotoc_md151", null ],
      [ "Status", "library_containers_reflection.html#autotoc_md152", null ],
      [ "Where To Go Next", "library_containers_reflection.html#autotoc_md153", null ],
      [ "Statistics", "library_containers_reflection.html#autotoc_md154", null ]
    ] ],
    [ "Fibers", "library_fibers.html", [
      [ "Dependencies", "library_fibers.html#autotoc_md155", null ],
      [ "Where Fibers Fits", "library_fibers.html#autotoc_md156", null ],
      [ "The Scheduling Model", "library_fibers.html#autotoc_md157", null ],
      [ "A Representative CPU Workload", "library_fibers.html#autotoc_md158", null ],
      [ "Stackless Jobs", "library_fibers.html#autotoc_md159", null ],
      [ "Capacity Is Part of Control Flow", "library_fibers.html#autotoc_md160", null ],
      [ "Adding Worker Threads", "library_fibers.html#autotoc_md161", null ],
      [ "Choosing Task and Stack Storage", "library_fibers.html#autotoc_md162", null ],
      [ "Stack Class Sizing", "library_fibers.html#autotoc_md163", null ],
      [ "Waiting, Coordination, and Cancellation", "library_fibers.html#autotoc_md164", null ],
      [ "Lifetime and Thread-Local State", "library_fibers.html#autotoc_md165", null ],
      [ "Allocation Policy", "library_fibers.html#autotoc_md166", null ],
      [ "Relationship to Neighboring Libraries", "library_fibers.html#autotoc_md167", null ],
      [ "API Reference", "library_fibers.html#autotoc_md168", null ],
      [ "Further Examples", "library_fibers.html#autotoc_md169", null ],
      [ "Status", "library_fibers.html#autotoc_md170", null ],
      [ "Statistics", "library_fibers.html#autotoc_md171", null ]
    ] ],
    [ "FibersAsync", "library_fibers_async.html", [
      [ "Dependencies", "library_fibers_async.html#autotoc_md172", null ],
      [ "The bridge, not another runtime", "library_fibers_async.html#autotoc_md173", null ],
      [ "A complete wait", "library_fibers_async.html#autotoc_md174", null ],
      [ "What the I/O calls return", "library_fibers_async.html#autotoc_md175", null ],
      [ "Memory and lifetime are part of the API", "library_fibers_async.html#autotoc_md176", null ],
      [ "Worker threads and the event-loop owner", "library_fibers_async.html#autotoc_md177", null ],
      [ "Cancellation and shutdown", "library_fibers_async.html#autotoc_md178", null ],
      [ "Choosing between the neighboring libraries", "library_fibers_async.html#autotoc_md179", null ],
      [ "Status and practical limits", "library_fibers_async.html#autotoc_md180", null ],
      [ "Roadmap", "library_fibers_async.html#autotoc_md181", null ],
      [ "Statistics", "library_fibers_async.html#autotoc_md182", null ]
    ] ],
    [ "File", "library_file.html", [
      [ "Dependencies", "library_file.html#autotoc_md183", null ],
      [ "When to use File", "library_file.html#autotoc_md184", null ],
      [ "A descriptor is an owned byte stream", "library_file.html#autotoc_md185", [
        [ "Reads, EOF and positions", "library_file.html#autotoc_md186", null ],
        [ "Metadata, durability and resizing", "library_file.html#autotoc_md187", null ]
      ] ],
      [ "Pipes: descriptors for process communication", "library_file.html#autotoc_md188", null ],
      [ "Named pipes: discoverable local endpoints", "library_file.html#autotoc_md189", null ],
      [ "Boundaries and tradeoffs", "library_file.html#autotoc_md190", null ],
      [ "Status", "library_file.html#autotoc_md191", null ],
      [ "Blog", "library_file.html#autotoc_md192", null ],
      [ "Roadmap", "library_file.html#autotoc_md193", null ],
      [ "Statistics", "library_file.html#autotoc_md194", null ]
    ] ],
    [ "File System", "library_file_system.html", [
      [ "Dependencies", "library_file_system.html#autotoc_md195", null ],
      [ "When to use File System", "library_file_system.html#autotoc_md196", null ],
      [ "The mental model: a private path base", "library_file_system.html#autotoc_md197", null ],
      [ "Storage, lifetime and failure behavior", "library_file_system.html#autotoc_md198", null ],
      [ "Paths, encodings and the low-level escape hatch", "library_file_system.html#autotoc_md199", null ],
      [ "Metadata and links require deliberate semantics", "library_file_system.html#autotoc_md200", null ],
      [ "Boundaries and tradeoffs", "library_file_system.html#autotoc_md201", null ],
      [ "Status", "library_file_system.html#autotoc_md202", null ],
      [ "Blog", "library_file_system.html#autotoc_md203", null ],
      [ "Roadmap", "library_file_system.html#autotoc_md204", null ],
      [ "Statistics", "library_file_system.html#autotoc_md205", null ]
    ] ],
    [ "File System Iterator", "library_file_system_iterator.html", [
      [ "Dependencies", "library_file_system_iterator.html#autotoc_md206", null ],
      [ "The traversal model", "library_file_system_iterator.html#autotoc_md207", null ],
      [ "Choosing recursion explicitly", "library_file_system_iterator.html#autotoc_md208", null ],
      [ "Memory, paths, and lifetime", "library_file_system_iterator.html#autotoc_md209", null ],
      [ "Where it fits", "library_file_system_iterator.html#autotoc_md210", null ],
      [ "Status and examples", "library_file_system_iterator.html#autotoc_md211", null ],
      [ "API reference", "library_file_system_iterator.html#autotoc_md212", null ],
      [ "Statistics", "library_file_system_iterator.html#autotoc_md213", null ]
    ] ],
    [ "File System Watcher", "library_file_system_watcher.html", [
      [ "Dependencies", "library_file_system_watcher.html#autotoc_md214", null ],
      [ "When it is a good fit", "library_file_system_watcher.html#autotoc_md215", null ],
      [ "Mental model", "library_file_system_watcher.html#autotoc_md216", null ],
      [ "A representative threaded watch", "library_file_system_watcher.html#autotoc_md217", null ],
      [ "Storage, limits, and lifetime", "library_file_system_watcher.html#autotoc_md218", null ],
      [ "Platform behavior worth designing for", "library_file_system_watcher.html#autotoc_md219", null ],
      [ "How it fits with neighboring libraries", "library_file_system_watcher.html#autotoc_md220", null ],
      [ "Status and further material", "library_file_system_watcher.html#autotoc_md221", null ],
      [ "Statistics", "library_file_system_watcher.html#autotoc_md222", null ]
    ] ],
    [ "Foundation", "library_foundation.html", [
      [ "Dependencies", "library_foundation.html#autotoc_md223", null ],
      [ "The mental model", "library_foundation.html#autotoc_md224", null ],
      [ "Representative use", "library_foundation.html#autotoc_md225", null ],
      [ "Allocation, errors, and lifetime", "library_foundation.html#autotoc_md226", null ],
      [ "Where Foundation stops", "library_foundation.html#autotoc_md227", null ],
      [ "Portability layer", "library_foundation.html#autotoc_md228", null ],
      [ "Maturity", "library_foundation.html#autotoc_md229", null ],
      [ "Blog", "library_foundation.html#autotoc_md230", null ],
      [ "Roadmap", "library_foundation.html#autotoc_md231", null ],
      [ "Statistics", "library_foundation.html#autotoc_md232", null ]
    ] ],
    [ "Hashing", "library_hashing.html", [
      [ "Dependencies", "library_hashing.html#autotoc_md233", null ],
      [ "When Hashing fits", "library_hashing.html#autotoc_md234", null ],
      [ "A hash is one incremental session", "library_hashing.html#autotoc_md235", null ],
      [ "Storage, allocation and lifetime", "library_hashing.html#autotoc_md236", null ],
      [ "Platform and integration boundaries", "library_hashing.html#autotoc_md237", null ],
      [ "Status", "library_hashing.html#autotoc_md238", null ],
      [ "Roadmap", "library_hashing.html#autotoc_md239", null ],
      [ "Statistics", "library_hashing.html#autotoc_md240", null ]
    ] ],
    [ "Http", "library_http.html", [
      [ "Dependencies", "library_http.html#autotoc_md241", null ],
      [ "The model: messages moving through fixed storage", "library_http.html#autotoc_md242", null ],
      [ "Choosing memory limits", "library_http.html#autotoc_md243", null ],
      [ "Representative server", "library_http.html#autotoc_md244", null ],
      [ "Representative client", "library_http.html#autotoc_md245", null ],
      [ "Protocol helpers and deliberate boundaries", "library_http.html#autotoc_md246", null ],
      [ "Operational notes", "library_http.html#autotoc_md247", null ],
      [ "Further material", "library_http.html#autotoc_md248", null ],
      [ "API reference", "library_http.html#autotoc_md249", [
        [ "HttpAsyncServer", "library_http.html#autotoc_md250", null ],
        [ "HttpAsyncFileServer", "library_http.html#autotoc_md251", null ],
        [ "HttpAsyncClient", "library_http.html#autotoc_md252", null ]
      ] ],
      [ "Statistics", "library_http.html#autotoc_md253", null ]
    ] ],
    [ "Http Client", "library_http_client.html", [
      [ "Dependencies", "library_http_client.html#autotoc_md254", null ],
      [ "Is HttpClient the right layer?", "library_http_client.html#autotoc_md255", null ],
      [ "The request is a description; the operation owns the conversation", "library_http_client.html#autotoc_md256", null ],
      [ "Request bodies and response metadata", "library_http_client.html#autotoc_md257", null ],
      [ "Optional state and event-loop layers", "library_http_client.html#autotoc_md258", null ],
      [ "Backend policy and current limits", "library_http_client.html#autotoc_md259", null ],
      [ "Where to look next", "library_http_client.html#autotoc_md260", null ],
      [ "Statistics", "library_http_client.html#autotoc_md261", null ]
    ] ],
    [ "Memory", "library_memory.html", [
      [ "Dependencies", "library_memory.html#autotoc_md262", null ],
      [ "When Memory Is The Right Layer", "library_memory.html#autotoc_md263", null ],
      [ "The Mental Model: Storage Policy Is Visible", "library_memory.html#autotoc_md264", null ],
      [ "Byte Storage: Buffer And SmallBuffer", "library_memory.html#autotoc_md265", null ],
      [ "Owning Strings Are Here For A Reason", "library_memory.html#autotoc_md266", null ],
      [ "Put A Bound Around A Subsystem", "library_memory.html#autotoc_md267", null ],
      [ "Reserve Address Space, Commit Physical Memory Later", "library_memory.html#autotoc_md268", null ],
      [ "Relationship To Neighboring Libraries", "library_memory.html#autotoc_md269", null ],
      [ "Status And Limits", "library_memory.html#autotoc_md270", null ],
      [ "Further Reading", "library_memory.html#autotoc_md271", null ],
      [ "Roadmap", "library_memory.html#autotoc_md272", null ],
      [ "Statistics", "library_memory.html#autotoc_md273", null ]
    ] ],
    [ "Plugin", "library_plugin.html", [
      [ "Dependencies", "library_plugin.html#autotoc_md274", null ],
      [ "The model: source tree to live instance", "library_plugin.html#autotoc_md275", null ],
      [ "A representative host loop", "library_plugin.html#autotoc_md276", null ],
      [ "The plugin-side contract", "library_plugin.html#autotoc_md277", null ],
      [ "Allocation and lifetime boundaries", "library_plugin.html#autotoc_md278", null ],
      [ "Linking against the host", "library_plugin.html#autotoc_md279", null ],
      [ "Relationships and tradeoffs", "library_plugin.html#autotoc_md280", null ],
      [ "Platform status and practical limits", "library_plugin.html#autotoc_md281", null ],
      [ "Further reading", "library_plugin.html#autotoc_md282", null ],
      [ "Statistics", "library_plugin.html#autotoc_md283", null ]
    ] ],
    [ "Process", "library_process.html", [
      [ "Dependencies", "library_process.html#autotoc_md284", null ],
      [ "When to use Process", "library_process.html#autotoc_md285", null ],
      [ "One object is one child launch", "library_process.html#autotoc_md286", [
        [ "Storage and hard limits", "library_process.html#autotoc_md287", null ]
      ] ],
      [ "Pipelines are intrusive and caller-owned", "library_process.html#autotoc_md288", null ],
      [ "Environment and working directory", "library_process.html#autotoc_md289", null ],
      [ "Fork is a specialized snapshot primitive", "library_process.html#autotoc_md290", null ],
      [ "Boundaries and neighboring libraries", "library_process.html#autotoc_md291", null ],
      [ "Status", "library_process.html#autotoc_md292", null ],
      [ "Videos", "library_process.html#autotoc_md293", null ],
      [ "Blog", "library_process.html#autotoc_md294", null ],
      [ "Roadmap", "library_process.html#autotoc_md295", null ],
      [ "Statistics", "library_process.html#autotoc_md296", null ]
    ] ],
    [ "Reflection", "library_reflection.html", [
      [ "Dependencies", "library_reflection.html#autotoc_md297", null ],
      [ "When Reflection Fits", "library_reflection.html#autotoc_md298", null ],
      [ "The Description You Write", "library_reflection.html#autotoc_md299", null ],
      [ "Two Ways Consumers Use It", "library_reflection.html#autotoc_md300", null ],
      [ "Packing Is a Serialization Property", "library_reflection.html#autotoc_md301", null ],
      [ "Allocation, Ownership, and Lifetime", "library_reflection.html#autotoc_md302", null ],
      [ "Relationship to Neighboring Libraries", "library_reflection.html#autotoc_md303", null ],
      [ "Status and Practical Limits", "library_reflection.html#autotoc_md304", null ],
      [ "Statistics", "library_reflection.html#autotoc_md305", null ]
    ] ],
    [ "SerialPort", "library_serial_port.html", [
      [ "Dependencies", "library_serial_port.html#autotoc_md324", null ],
      [ "When SerialPort fits", "library_serial_port.html#autotoc_md325", null ],
      [ "A serial port is a configured file descriptor", "library_serial_port.html#autotoc_md326", [
        [ "Settings describe intent, drivers decide what is possible", "library_serial_port.html#autotoc_md327", null ]
      ] ],
      [ "Blocking, Async, and ownership boundaries", "library_serial_port.html#autotoc_md328", null ],
      [ "Boundaries and tradeoffs", "library_serial_port.html#autotoc_md329", null ],
      [ "Status", "library_serial_port.html#autotoc_md330", null ],
      [ "Testing a real Windows COM pair", "library_serial_port.html#autotoc_md331", null ],
      [ "Blog", "library_serial_port.html#autotoc_md332", null ],
      [ "Roadmap", "library_serial_port.html#autotoc_md333", null ],
      [ "Statistics", "library_serial_port.html#autotoc_md334", null ]
    ] ],
    [ "Serialization Binary", "library_serialization_binary.html", [
      [ "Dependencies", "library_serialization_binary.html#autotoc_md306", null ],
      [ "The decision this library makes", "library_serialization_binary.html#autotoc_md307", null ],
      [ "A representative reflected model", "library_serialization_binary.html#autotoc_md308", null ],
      [ "What versioned loading can and cannot absorb", "library_serialization_binary.html#autotoc_md309", null ],
      [ "Storage, allocation, and lifetime", "library_serialization_binary.html#autotoc_md310", null ],
      [ "Binary layout and the packed fast path", "library_serialization_binary.html#autotoc_md311", null ],
      [ "Fit with neighboring libraries", "library_serialization_binary.html#autotoc_md312", null ],
      [ "Current limits", "library_serialization_binary.html#autotoc_md313", null ],
      [ "API reference", "library_serialization_binary.html#autotoc_md314", null ],
      [ "Statistics", "library_serialization_binary.html#autotoc_md315", null ]
    ] ],
    [ "Serialization Text", "library_serialization_text.html", [
      [ "Dependencies", "library_serialization_text.html#autotoc_md316", null ],
      [ "When It Fits", "library_serialization_text.html#autotoc_md317", null ],
      [ "The Model: Reflection Drives The Walk", "library_serialization_text.html#autotoc_md318", null ],
      [ "Choose The Read Contract Deliberately", "library_serialization_text.html#autotoc_md319", null ],
      [ "Storage, Allocation, And Lifetime", "library_serialization_text.html#autotoc_md320", null ],
      [ "Boundaries And Neighboring Libraries", "library_serialization_text.html#autotoc_md321", null ],
      [ "API Reference", "library_serialization_text.html#autotoc_md322", null ],
      [ "Statistics", "library_serialization_text.html#autotoc_md323", null ]
    ] ],
    [ "Socket", "library_socket.html", [
      [ "Dependencies", "library_socket.html#autotoc_md335", null ],
      [ "When to use Socket", "library_socket.html#autotoc_md336", null ],
      [ "The handle is the socket; client and server are views", "library_socket.html#autotoc_md337", null ],
      [ "Addresses, DNS and process initialization", "library_socket.html#autotoc_md338", null ],
      [ "Reading and writing are single synchronous operations", "library_socket.html#autotoc_md339", null ],
      [ "UDP, broadcast and multicast", "library_socket.html#autotoc_md340", null ],
      [ "Boundaries and tradeoffs", "library_socket.html#autotoc_md341", null ],
      [ "Status", "library_socket.html#autotoc_md342", null ],
      [ "Blog", "library_socket.html#autotoc_md343", null ],
      [ "Roadmap", "library_socket.html#autotoc_md344", null ],
      [ "Statistics", "library_socket.html#autotoc_md345", null ]
    ] ],
    [ "Strings", "library_strings.html", [
      [ "Dependencies", "library_strings.html#autotoc_md346", null ],
      [ "Status", "library_strings.html#autotoc_md347", null ],
      [ "Start With The Text Model", "library_strings.html#autotoc_md348", null ],
      [ "Views Are Cheap, But Their Contracts Matter", "library_strings.html#autotoc_md349", null ],
      [ "Build Into Storage Chosen By The Caller", "library_strings.html#autotoc_md350", null ],
      [ "Convert Only At Encoding Boundaries", "library_strings.html#autotoc_md351", null ],
      [ "Paths Are Lexical Strings, Not Filesystem Operations", "library_strings.html#autotoc_md352", null ],
      [ "Command Lines And Console Output", "library_strings.html#autotoc_md353", null ],
      [ "Allocation, Lifetime, And Failure", "library_strings.html#autotoc_md354", null ],
      [ "Boundaries With Neighboring Libraries", "library_strings.html#autotoc_md355", null ],
      [ "What Is Deliberately Missing", "library_strings.html#autotoc_md356", null ],
      [ "Blog", "library_strings.html#autotoc_md357", null ],
      [ "Roadmap", "library_strings.html#autotoc_md358", null ],
      [ "Statistics", "library_strings.html#autotoc_md359", null ]
    ] ],
    [ "Testing", "library_testing.html", [
      [ "Dependencies", "library_testing.html#autotoc_md360", null ],
      [ "The execution model", "library_testing.html#autotoc_md361", null ],
      [ "Building a runner", "library_testing.html#autotoc_md362", null ],
      [ "Selecting work from the command line", "library_testing.html#autotoc_md363", null ],
      [ "Failure and lifetime behavior", "library_testing.html#autotoc_md364", null ],
      [ "Fit and neighboring libraries", "library_testing.html#autotoc_md365", null ],
      [ "Status and direction", "library_testing.html#autotoc_md366", null ],
      [ "Statistics", "library_testing.html#autotoc_md367", null ]
    ] ],
    [ "Threading", "library_threading.html", [
      [ "Dependencies", "library_threading.html#autotoc_md368", null ],
      [ "When Threading Fits", "library_threading.html#autotoc_md369", null ],
      [ "Threads Have Explicit Terminal Ownership", "library_threading.html#autotoc_md370", null ],
      [ "Choosing A Synchronization Primitive", "library_threading.html#autotoc_md371", null ],
      [ "A Bounded-By-Ownership Thread Pool", "library_threading.html#autotoc_md372", null ],
      [ "Atomics Are Intentionally Narrow", "library_threading.html#autotoc_md373", null ],
      [ "Relationship To Neighboring Libraries", "library_threading.html#autotoc_md374", null ],
      [ "Status And Further Material", "library_threading.html#autotoc_md375", null ],
      [ "Roadmap", "library_threading.html#autotoc_md376", null ],
      [ "Statistics", "library_threading.html#autotoc_md377", null ]
    ] ],
    [ "Time", "library_time.html", [
      [ "Dependencies", "library_time.html#autotoc_md378", null ],
      [ "Choosing The Right Clock", "library_time.html#autotoc_md379", null ],
      [ "Measuring And Comparing Time", "library_time.html#autotoc_md380", null ],
      [ "Wall-Clock Timestamps And Calendar Fields", "library_time.html#autotoc_md381", null ],
      [ "Allocation, Lifetime, And Portability", "library_time.html#autotoc_md382", null ],
      [ "Fit And Current Limits", "library_time.html#autotoc_md383", null ],
      [ "API Reference", "library_time.html#autotoc_md384", null ],
      [ "Further Reading", "library_time.html#autotoc_md385", null ],
      [ "Statistics", "library_time.html#autotoc_md386", null ]
    ] ]
];